# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Example
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTWebSocket',
  ]
  pod 'RCTAMap', :path => '../../ios'

end
