# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RCTAMap' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RCTAMapView
  pod 'AMap3DMap'
  pod 'AMapSearch'
  pod 'AMapLocation'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTWebSocket',
  ]

end
